tests: NetworkProperties test coverage
mattdibi/kura pull request #3
Opened 2023-01-31 22:42 UTC by GregoryIvo

WIP

**Related Issue:** n/a

**Description of the solution adopted:** n/a

**Screenshots:** n/a

**Any side note on the changes made:** n/a

2023-02-01 18:29 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +		thenCompareGetPropertiesToPassedProperties();
I like where this is going but take a look here for a more flexible approach: https://github.com/eclipse/kura/blob/develop/kura/test/org.eclipse.kura.ai.triton.server.test/src/test/java/org/eclipse/kura/ai/triton/server/TritonServerServiceOptionsTest.java

With `givenTheTestProperties` the reader of the code must go to the bottom of the file to understand what's the content of the Map. If you go for the approach of the link I just gave you you would have something like:

```suggestion
		givenMapWith("testKey1", "testString1");
		givenMapWith("testKeyNull", null);
		givenNetworkPropertiesBuiltWith(this.map);
		
		then...
```

which is more readable and flexible

2023-02-01 19:08 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +		givenTheMapWith("testKey-comma-seperated", "commaSeperated1,commaSeperated2,commaSeperated3");
Also don't be afraid to break the code... Try out more unhappy paths like: what happens when the map is built with a string like `"commaSeparated1,,commaSeparated3"`? As we said in the meeting we're interested in testing thoroughly possible edge cases and finding bugs **here** instead of in production.

2023-02-01 19:14 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	public void whenNetworkPropsIsCreated() {
IMO This is still a `given` i.e. is part of the test setup.

> In the GIVEN clause, you should express any kind of setup conditions that are necessary for this test to succeed. This encompasses hardware conditions as well as data, files, or records that must have a specific condition for the test to run.

So:

```suggestion
	public void giveNetworkPropsIsCreated() {
```

or

```suggestion
	public void giveNetworkPropsIsCreatedWith(Map<String, Object> props) {
```

2023-02-01 19:23 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +		thenGetReturnsExpectedObjectWithKey("testKey1");
I find it hard to follow what is tested here. It's similar to what we had with the `given` stuff  in that I have to go at the bottom of the file to understand what is the expected object.

How about something like:

```suggestion
                whenGetIsCalledWith("testKey1", String.class);
                
                thenNoExceptionOccurred();
                thenTheResultIsNotNull();
                thenTheResultBelongsTo(String.class);
                thenTheResultIsEqualTo("testString1");
```

again: more readable, more flexible and easier to debug.

Please note that not all the method here make sense (the "belongtoclass" doesn't convince me), try to find out the ones that work for you.

2023-02-01 20:36 UTC, GregoryIvo commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	public void whenNetworkPropsIsCreated() {
I think I disagree with this. In this step, we "configure the system" that we are going to test—by instantiating and applying the config?  ("by creating and configuring our object to test")

Thoughts?

2023-02-01 21:55 UTC, GregoryIvo commented
Thank you @mattdibi for taking the time to give me a good solid review. I really appreciate you going out of your way to teach me how to do this properly.  😄

2023-02-03 07:45 UTC, mattdibi requested changes
The code so far looks *great* to me.

I think there's still come test case missing. Off the top of my head:
- What happens when you call `get` on a key that's missing from the map?
- What happens when you call `get` on a key that is storing a `null` value?
- What happens when you call `getStringList` on a key that's missing from the map?
- What happens when you call `getStringList` on a key that is storing a `null` value?

... try and see if there's still some more edge cases missing...

2023-02-03 07:49 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	}
Additionally this is not completely adherent to our Gerkhin-style testing guidelines.

It should be something like:
```suggestion
	public void shouldFailWhenNull() {
		givenNetworkPropertiesBuiltWith(null);
		givenNetworkPropsIsCreated();
		thenNullPointerExceptionIsThrown()
	}
```

Look ad what we did [here](https://github.com/eclipse/kura/blob/develop/kura/test/org.eclipse.kura.ai.triton.server.test/src/test/java/org/eclipse/kura/ai/triton/server/TritonServerEncryptionUtilsTest.java) with the `thenAnExceptionOccurred`... it would be nice if you checked for what kind of exception is thrown though.

2023-02-03 07:51 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +
... There's an extra newline here...

```suggestion
```

2023-02-03 07:53 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	// Given //
Finally (and this is my OCD that's talking) in the past we used the following comment style for splitting the Gerkhin-style sections:

```suggestion
     /*
     * Given
     */
```

2023-02-03 13:58 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +		thenResultEquals(List.of("commaSeperated1", "commaSeperated2", "commaSeperated3"));
This is weird... `List.of` is a method introduced in Java9... it doesn't compile for me. Are your IDE settings correct?

Replace every `List.of` with `Arrays.asList`

```suggestion
		thenResultEquals(Arrays.asList("commaSeperated1", "commaSeperated2", "commaSeperated3"));
```

2023-02-03 14:43 UTC, GregoryIvo commented
With these changes, it is now compiling on java 8.

2023-02-03 15:24 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +		thenAnNoSuchElementExceptionOccured();
Shouldn't this be `thenA...` and not `thenAn`?

```suggestion
		thenANoSuchElementExceptionOccured();
```

> The rule is: Use "an" before a word beginning with a vowel sound (not letter)

2023-02-03 15:25 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +		thenAnNullPointerExceptionOccured();
Also here maybe?

```suggestion
		thenANullPointerExceptionOccured();
```

2023-02-03 15:29 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +		properties = new HashMap<String, Object>();
This should be moved instantiated in the class field. At every test case the class is cleared out of any data.

Having the instantiation in the class field will allow you to have the following in the test cases:

```
givenTheMapWith("testKeyNull", null);
givenTheMapWith("testKey1", "testString1");
givenTheMapWith("testKey-comma-seperated",
				", , ,,,,commaSeperated1, , , ,,,,,commaSeperated2,,,, ,, ,,commaSeperated3,, , ,,,, ,");
givenNetworkPropsIsCreated();
```

2023-02-03 15:31 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	Map<String, Object> properties;
Referring to https://github.com/mattdibi/kura/pull/3/files#r1095931931

```suggestion
	Map<String, Object> properties = new HashMap<String, Object>();
```

2023-02-03 15:35 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +		properties = new HashMap<String, Object>();
When you fix this I'll also propose to add a few test cases with multiple keys... are there relevant test cases to be made in that scenario?

2023-02-03 15:47 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	public void givenTheMapWith(String key, Object pair) {
Finally... this is just a style preference, what do you think of:

```suggestion
	public void givenMapWith(String key, Object pair) {
```

2023-02-03 15:50 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +		thenResultEquals(Collections.singletonMap("testKey1", "testString1"));
You should also check that no exception occurred for each tests where you expect it, right?

```suggestion
		thenNoExceptionOccurred();
		thenResultEquals(Collections.singletonMap("testKey1", "testString1"));
```

2023-02-03 15:51 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	public void givenTheMapWith(String key, Object pair) {
I keep saying "finally" but we both know I'm lying XD

2023-02-03 21:13 UTC, GregoryIvo commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +		thenAnNoSuchElementExceptionOccured();
I was torn between grammar and proper CamelCase.  and CamelCase won....

2023-02-03 21:18 UTC, GregoryIvo commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +		properties = new HashMap<String, Object>();
This is a fun fact I did not know. Very good to know

2023-02-04 08:19 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +		properties = new HashMap<String, Object>();
Excellent! This unit tests are proving extremely valuable for you then... [Here](https://martinfowler.com/bliki/JunitNewInstance.html) you can find a good write-up about this behaviour.

2023-02-04 08:23 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +		thenNoExceptionsOccured();
One thing that just came to my mind: the order of the statements here is important.

What happens if, because of a wrong refactoring, the constructor of the `NetworkProperties` throws? You'll get the error on `thenResultEquals` because you're comparing with a `null` but **no indication about the thrown exception** because the excecution of the test stops at the first error. This would lead to a hard time to whoever is debugging because it would check for a `null` map returned instead of a thrown exception!

2023-02-06 12:58 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +
Remove unused method

```suggestion
```

2023-02-06 12:59 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +			this.hasNoSuchElementExceptionBeenThrown = false;
As per https://github.com/mattdibi/kura/pull/3#discussion_r1095931931 this statements are redundant

```suggestion
```

2023-02-06 13:06 UTC, GregoryIvo commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +
<img width="582" alt="image" src="https://user-images.githubusercontent.com/29900100/216978942-b6def3c3-f9d2-4509-bf8a-537fb73841bb.png">

It is used? Should I still keep it

2023-02-06 13:10 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +
Oh sorry... I would then merge the two methods `givenNetworkPropertiesBuiltWith` and `givenNetworkPropsIsCreated` into something like:

```java
public void givenNetworkPropertiesBuiltWith(Map<String, Object> properties) {

		try {
			netProps = new NetworkProperties(properties);

		} catch (NullPointerException e) {
			this.hasNullPointExceptionBeenThrown = true;
		} catch (NoSuchElementException e) {
			this.hasNoSuchElementExceptionBeenThrown = true;
		}
	}
```

so that you can either pass it `null` for this test or `this.properties` for everything else.

2023-02-06 13:14 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	public void shouldFailWhenWmpty() {
Typo

```suggestion
	public void shouldFailWhenEmpty() {
```

2023-02-06 13:44 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	}
Please use meaningful names for these methods and avoid overloading them

2023-02-06 13:50 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +		whenGetIsCalledWith("", String.class);
I've only seen tests on `String`s so far. Please expand your tests to cover more classes (`Boolean`, `Short`, `Integer`, `Long`).

The same goes for the `getOpt` method unit tests.

2023-02-06 15:10 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +		thenShortResultEquals((short) 10);
Use class constructors instead of casting

```suggestion
		thenShortResultEquals(new Short(10));
```

2023-02-06 15:20 UTC, GregoryIvo commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +		thenShortResultEquals((short) 10);
are you sure? some of the constructors are deprecated? 

IE
<img width="218" alt="image" src="https://user-images.githubusercontent.com/29900100/217011103-45bee51e-2bc2-469b-aa56-ff85d5aa426a.png">

2023-02-06 15:35 UTC, GregoryIvo commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +		thenShortResultEquals((short) 10);
<img width="359" alt="image" src="https://user-images.githubusercontent.com/29900100/217014754-7bc8d486-2673-4ff8-86ba-3000308570ed.png">

2023-02-06 15:35 UTC, GregoryIvo commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +		thenShortResultEquals((short) 10);
<img width="359" alt="image" src="https://user-images.githubusercontent.com/29900100/217014754-7bc8d486-2673-4ff8-86ba-3000308570ed.png">

2023-02-06 15:36 UTC, GregoryIvo commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +		thenShortResultEquals((short) 10);
They are deprecated since version 9. Will this be an issue for java 17?

2023-02-06 16:17 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	String stringResult; // Boolean, Short, Integer, Long
Remove unnecessary comment.

```suggestion
	String stringResult;
```

2023-02-06 16:39 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	public void shouldReturnStringWithGetMissing() {
```suggestion
	public void shouldThrowWithGetMissing() {
```

2023-02-06 16:40 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	public void shouldReturnStringWithGetNull() {
```suggestion
	public void shouldThrowWithGetNull() {
```

2023-02-06 16:40 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	public void shouldFailWhenEmpty() {
```suggestion
	public void shouldWorkWithEmptyMap() {
```

2023-02-06 16:41 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	public void shouldFailWhenNull() {
```suggestion
	public void shouldThrowWithNullMap() {
```

2023-02-06 16:42 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	public void shouldReturnStringListGetStringListWithCommaSeperatedStringNull() {
```suggestion
	public void shouldThrowListGetStringListWithCommaSeperatedStringNull() {
```

2023-02-06 16:42 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	public void shouldReturnStringListGetStringListWithCommaSeperatedStringMissing() {
```suggestion
	public void shouldThrowGetStringListWithCommaSeperatedStringMissing() {
```

2023-02-06 16:43 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	}
Actually, we expect this to throw an exception. Don't we?

2023-02-07 07:53 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	}
I think here we got a little confused...

`get` should work properly with an empty string as **key**... but it should throw if the **value** is an empty string. Does this make sense to you?

2023-02-07 08:08 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	int intResult;
Use primitive wrapper for coherence

```suggestion
	Integer intResult;
```

2023-02-07 08:23 UTC, mattdibi requested changes
Apart from the already mentioned issues, I'm still not happy with the test case names. Please review them such they all follow the same convention:

`[tested method name][ShouldWork/ShouldThrow][test condition]`

I will now provide you with a few more examples using the Github suggestions.

We're almost there!

2023-02-07 08:24 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	public void shouldThrowWithNullMap() {
What method are we testing here?

```suggestion
	public void constructorShouldThrowWithNullMap() {
```

2023-02-07 08:24 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	public void shouldWorkWithEmptyMap() {
What method are we testing here?

```suggestion
	public void getPropertiesShouldWorkWithEmptyMap() {
```

2023-02-07 08:31 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	public void getShouldReturnString() {
What are the testing conditions?

```suggestion
	public void getShouldWorkWithString() {
```

2023-02-07 08:31 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	public void getShouldThrowWithMissing() {
More detailed name:

```suggestion
	public void getShouldThrowWithMissingKey() {
```

2023-02-07 08:32 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	public void getShouldReturnBoolean() {
```suggestion
	public void getShouldWorkWithBoolean() {
```

2023-02-07 08:33 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	public void getOptWithNullShouldReturnEmpty() {
```suggestion
	public void getOptShouldWorkWithNullValue() {
```

2023-02-07 08:33 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	public void getStringListShouldReturnStringListGetStringList() {
```suggestion
	public void getStringListShouldWorkWithSimpleMap() {
```

2023-02-07 08:34 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	public void getStringListShouldReturnStringList() {
```suggestion
	public void getStringListShouldWorkWithMultipleCommas() {
```

2023-02-07 08:34 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	public void getStringListShouldThrow() {
```suggestion
	public void getStringListShouldThrowWithNullValue() {
```

2023-02-07 08:35 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	public void getStringListShouldReturnStringListWithOneItem() {
```suggestion
	public void getStringListShouldWorkWithNoCommas() {
```

2023-02-07 08:35 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	public void getStringListShouldReturnStringListWithNull() {
```suggestion
	public void getStringListShouldThrowWithNullValue() {
```

2023-02-07 08:36 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	public void getStringListShouldReturnOptionalStringListWithCommaSeperatedString() {
```suggestion
	public void getOptStringListShouldWorkWithSimpleMap() {
```

2023-02-07 08:36 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	public void getStringListShouldReturnOptionalStringListtWithCommaSeperatedStringMalformed() {
```suggestion
	public void getOptStringListShouldWorkWithMultipleCommas() {
```

2023-02-07 08:37 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	public void getStringListShouldReturnOptionalStringListWithString() {
```suggestion
	public void getOptStringListShouldWorkWithNoCommas() {
```

2023-02-07 08:38 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	public void getStringListShouldThrowWithNull() {
This isn't our expectation. `getOptStringList` should return `Optional.empty` if the value is null.

```suggestion
	public void getStringListShouldWorkWithNullValue() {
```

2023-02-07 08:39 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	public void getStringListShouldThrowWithNoKey() {
This isn't our expectation. `getOptStringList` should return `Optional.empty` if the key is missing.

```suggestion
	public void getStringListShouldWorkWithMissingKey() {
```

2023-02-07 08:39 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	public void whenGetStringListOptIsCalledWith(String key) {
Please, follow the already established convention and use the correct method name:

```suggestion
	public void whenGetOptStringListIsCalledWith(String key) {
```

2023-02-07 08:42 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	public void getOptShouldReturnEmptyKey() {
```suggestion
	public void getOptShouldWorkWithEmptyKey() {
```

2023-02-08 21:32 UTC, GregoryIvo commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	}
I tried to capture this in my latest PR, tell me what you think!

2023-02-09 11:33 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	}
Mh... this will need some discussion 🤔

2023-02-09 12:47 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	}
Thing is: the `get` method is for *mandatory* properties. I expect to find *meaningful informations* when calling this method. An empty string doesn't carry any meaningful information.

In the `getOpt` we do the same: the empty string translates to an `Optional.empty()` because, again, it doesn't carry any meaningful information.

The empty string for the *key* however, make sense (sort of). It is just an identifier for informations I want to access. It doesn't carry information, it's just a key in a map.

Does this make sense to you?

2023-02-09 12:53 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NetworkPropertiesTest.java
> +	}
Think about it from the user of the code perspective.

If `getOpt` can return an empty string I need to check:
- if the object `isPresent()`
- if the string `isEmpty()`

If `getOpt` behaves as it is doing now we only need to check for the `isPresent()`.

The same applies for the `get` method.

2023-02-09 16:30 UTC, mattdibi approved these changes

2023-02-09 16:30 UTC, merged