tests: initial implementation of NMSettingsConverterTest
mattdibi/kura pull request #5
Opened 2023-02-10 16:49 UTC by GregoryIvo

> **Note**: We are using the Conventional Commits convention for our pull request titles. Please take a look at the [PR title format document](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#submitting-the-changes) for the supported [types](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#type) and [scopes](https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md#scope).

Brief description of the PR. [e.g. Added `null` check on `object` to avoid `NullPointerException`]

**Related Issue:** This PR fixes/closes {issue number}

**Description of the solution adopted:** A more detailed description of the changes made to solve/close one or more issues. If the PR is simple and easy to understand this section can be skipped.

**Screenshots:** If applicable, add screenshots to help explain your solution

**Any side note on the changes made:** Description of any other change that has been made, which is not directly linked to the issue resolution [e.g. Code clean up/Sonar issue resolution]

2023-02-14 08:30 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NMSettingsConverterTest.java
> +				kuraNetType);
These two should be inside a `given` statement like:

```suggestion
		givenNetInterface("wlan0");
		givenIPStatus("netIPv4StatusUnmanaged");
		givenValidWifiConfigurationWithInterfaceNameAndDhcpBoolAndNetStatus(this.netInterface, false, this.kuraIPStatus);
		givenExpectedValidWifiConfigurationWithInterfaceNameAndDhcpBoolAndNetStatus(this.netInterface, false,
				this.kuraIPStatus);
```

2023-02-14 08:48 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NMSettingsConverterTest.java
> +		thenMapResultShouldEqualInternalMap();
Same thing here:

```suggestion
		thenResultingMapContains("method", "manual");
		thenResultingMapContains("ignore-auto-dns", true);
		thenResultingMapContains("gateway", "192.168.0.1");
		thenResultingAddressDataSizeIs(1);
		thenResultingAddressDataContains("192.168.0.12", 24)
```

2023-02-14 09:22 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NMSettingsConverterTest.java
> +	}
Don’t repeat the logic under test when verifying the expected result of tests. Instead, use known, hard-coded, pre-calculated values.

2023-02-14 09:25 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NMSettingsConverterTest.java
> +		whenBuildIpv4SettingsIsRunWithNetworkPropsAndIfaceString(this.networkProperties, "wlan0");
This name (and others around) are unnecessarily complicated and hard to read. We already know what arguments we're passing, they're right there...

```suggestion
		whenBuildIpv4SettingsIsRunWith(this.networkProperties, "wlan0");
```

2023-02-14 09:25 UTC, mattdibi requested changes
As I wrote in the comments this PR requires a lot of rework. The two main issues I have are:

- Don’t repeat the logic under test when verifying the expected result of tests. Instead, use known, hard-coded, pre-calculated values.
- Make the hard-coded, pre-calculated values more explicit and visible in the tests as per our discussions [here](https://github.com/mattdibi/kura/pull/5#discussion_r1105468171) and [here](https://github.com/mattdibi/kura/pull/5#discussion_r1105476536)

2023-02-14 13:06 UTC, GregoryIvo commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NMSettingsConverterTest.java
> +		whenBuildIpv4SettingsIsRunWithNetworkPropsAndIfaceString(this.networkProperties, "wlan0");
This satisfies that hardcoded  truths but also causes a lot of repetition?

2023-02-14 13:07 UTC, GregoryIvo commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NMSettingsConverterTest.java
> +		whenBuildIpv4SettingsIsRunWithNetworkPropsAndIfaceString(this.networkProperties, "wlan0");
If this is the case we might as well use map.put?

2023-02-14 13:23 UTC, GregoryIvo commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NMSettingsConverterTest.java
> +		whenBuildIpv4SettingsIsRunWithNetworkPropsAndIfaceString(this.networkProperties, "wlan0");
Wouldnt this kist be effectively using Map.put()?  It confines to being strongly hardcoded, but also will cause a bunch of repetition in tests, which I thought we were trying to avoid?

2023-02-14 13:34 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NMSettingsConverterTest.java
> +		whenBuildIpv4SettingsIsRunWithNetworkPropsAndIfaceString(this.networkProperties, "wlan0");
Yeah, in the end our `givenMapWith` is a thin wrapper around `map.put` but there shouldn't be much repetitions. The data in the map is what changes between test cases, isn't it? Maybe I'm missing something?

2023-02-14 13:57 UTC, GregoryIvo commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NMSettingsConverterTest.java
> +		whenBuildIpv4SettingsIsRunWithNetworkPropsAndIfaceString(this.networkProperties, "wlan0");
There's just so much boiler plate to change 1-2 vars in the map imho. 

I was thinking of just flattening my cases in the methods and making things more explicit. Hope this makes sense

2023-02-15 08:14 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NMSettingsConverterTest.java
> +		givenMapWith("net.interface." + this.netInterface + ".config.ip4.gateway", "192.168.0.1");
This is a little weird.

You're treating these 3 differently from the rest of the map parameters. Why?

I get what you're doing for the `netInterface` but the others? Is it because of [this comment here](https://github.com/mattdibi/kura/pull/5#discussion_r1105458031)?

I think you should get rid of `kuraIP4Status` and `KuraDhcpStatus` and use them like the other parameters.

```suggestion
		givenNetInterface("wlan0");
		givenMapWith("net.interface." + this.netInterface + ".config.dhcpClient4.enabled", false);
		givenMapWith("net.interface." + this.netInterface + ".config.ip4.status", "netIPv4StatusEnabledWAN");
		givenMapWith("net.interface." + this.netInterface + ".config.ip4.address", "192.168.0.12");
		givenMapWith("net.interface." + this.netInterface + ".config.ip4.prefix", (short) 25);
		givenMapWith("net.interface." + this.netInterface + ".config.ip4.dnsServers", "1.1.1.1");
		givenMapWith("net.interface." + this.netInterface + ".config.ip4.gateway", "192.168.0.1");
```

Furthermore I don't super like the string concatenation you have there.

If you want to keep using the `netInterface` variable it could be better to use `String.format` like you did before. Otherwise go full hardcoded and the rid of the `netInterface`. But this is nitpicking, you can leave it as-is if you want to.

2023-02-15 08:16 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NMSettingsConverterTest.java
> +	}
Typo on `Varient`, should be `Variant`:

```suggestion
	public Object buildAddressDataWith(String ipAddr, UInt32 prefix) {
		
		Map<String, Variant<?>> addressEntry = new HashMap<>();
		addressEntry.put("address", new Variant<>(ipAddr));
		addressEntry.put("prefix", new Variant<>(prefix));
		
		List<Map<String, Variant<?>>> addressData = Arrays.asList(addressEntry);
		
		Variant<?> dataVariant = new Variant<>(addressData, "aa{sv}");
		
		return dataVariant.getValue();
	}
```

2023-02-15 08:18 UTC, mattdibi commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NMSettingsConverterTest.java
> +	// given
Use the already established format:

```suggestion
     /*
     * Given
     */
```

2023-02-15 08:42 UTC, mattdibi requested changes
In addition to the other comments there are still two main issues:

- Coverage:
  - The tests where `Connection` is present are missing (I suggest you to use mocks for this).
  - What happens if the IP is not specified when setting the IP as static?
  - What happens if the prefix is not specified when setting the IP as static?
  - What happens if any of the mandatory values is `null`?
  - I updated the modifier of `buildConnectionSettings` to be `public` you can now test it separately as you did for the other methods
- There are unexpected failing tests:

![image](https://user-images.githubusercontent.com/22748355/218975633-6a061072-9865-4bc8-9a4a-9de9c6771f3b.png)

These methods throw `NoSuchElementException` not an `IllegalArgumentException`.

2023-02-15 13:09 UTC, GregoryIvo commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NMSettingsConverterTest.java
> +		givenMapWith("net.interface." + this.netInterface + ".config.ip4.gateway", "192.168.0.1");
I chaged from string format to not copy the implementation. I will hard code everything then.

2023-02-15 13:14 UTC, GregoryIvo commented on kura/test/org.eclipse.kura.nm.test/src/test/java/org/eclipse/kura/nm/configuration/NMSettingsConverterTest.java
> +		givenMapWith("net.interface." + this.netInterface + ".config.ip4.gateway", "192.168.0.1");
The goal with this was to save a future Devs fingers

2023-02-15 20:35 UTC, GregoryIvo commented
@mattdibi  Hi, I have introduced 4 new failing tests purposely because I think they might be covered.

Basically, some null vars related to WiFi security should probably not be allowed to be null.
Thoughts?

2023-02-15 21:42 UTC, GregoryIvo commented
@mattdibi pls review!
<img width="786" alt="image" src="https://user-images.githubusercontent.com/29900100/219174751-78731caf-d5fc-49ea-aeef-2dbfe4363d58.png">

2023-03-01 07:37 UTC, mattdibi commented
Superseded by https://github.com/eclipse/kura/pull/4380

2023-03-01 07:37 UTC, closed without merging